% This script is used to create a data file
%Run once and save the variables from the workspace
%save('HighLevelData.mat')

high_level_data = struct(...
'institution', 'Yale University',...
'experiment_description','Demonstrate bulk data imports of mouse position data and metadata',...
'lab', 'Tan Lab'...
);